---
 - name: Realizar BACKUP de Redmine
   hosts: produccion

   tasks:
     - name: Crear directorio
       file:
        path: "/home/ansible/redmineBackup"
        state: directory
     - name: Obtener id del container
       command: docker ps -qf "ancestor=bitnami/redmine:5"
       register: id_container
     - name: Almacenar id
       set_fact:
         id_var: id_container.stdout
     - name: Copiar directorio
       command: docker cp 7613a73c57a1:/bitnami/redmine /home/ansible/redmineBackup
